FROM python:3.7

RUN pip install poetry

RUN mkdir {{ apps_dir }}
RUN mkdir /{{ project_name }}

WORKDIR /{{ project_name }}
COPY poetry.lock pyproject.toml /{{ project_name }}/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /{{ project_name }}

CMD ["python3", "{{ server_script_path }}"]
