FROM python:3.7

RUN pip install poetry

RUN mkdir {{ mounted_apps_path }}
RUN mkdir /app_storage

WORKDIR /app_storage
COPY poetry.lock pyproject.toml /app_storage/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /app_storage

CMD ["python3", "server/app.py"]
