- hosts: local
  gather_facts: false

  vars:
    templates_path: "./templates"

  tasks:
    - name: ensure apps path exists
      file:
        path: "{{ apps_path }}"
        state: directory

    - name: setup env files
      template:
        src: "{{ templates_path }}/{{ item }}.j2"
        dest: "{{ project_path }}/{{ item }}"
      with_items:
        - ".env"
        - "ui.Dockerfile"
        - "nginx_config"
        - "unit.Dockerfile"
        - "unit_config.json"
        - "server.Dockerfile"
        - "docker-compose.yml"

    - name: run base services
      shell: docker-compose up -d db unit
      args:
        chdir: "{{ project_path }}"
