- hosts: remote
  gather_facts: false

  vars:
    templates_path: "./templates"

  tasks:
    - name: setup env files
      template:
        src: "{{ templates_path }}/{{ item }}.j2"
        dest: "{{ project_path }}/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - ".env"
        - "unit_config.json"
        - "unit.Dockerfile"
        - "server.Dockerfile"
        - "docker-compose.yml"

    - name: run services
      shell: docker-compose up -d --build --force-recreate db server unit
      args:
        chdir: "{{ project_path }}"

    - name: remove intermediate images
      shell: docker image prune --force
      args:
        chdir: "{{ project_path }}"
