- hosts: all
  gather_facts: false

  vars:
    templates_path: "./templates"

  tasks:
    - name: ensure project path exists
      file:
        path: "{{ project_path }}"
        state: directory

    - name: setup env files
      template:
        src: "{{ templates_path }}/{{ item }}.j2"
        dest: "{{ project_path }}/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - ".env"
        - "Dockerfile.server"
        - "Dockerfile.unit"
        - "Dockerfile.ui"
        - "docker-compose.yml"

    - name: ensure apps path exists
      file:
        path: "{{ apps_path }}"
        state: directory

    - name: run base services
      shell: docker-compose up -d db unit
      args:
        chdir: "{{ project_path }}"

    - name: run server
      shell: docker-compose up -d server ui
      args:
        chdir: "{{ project_path }}"
      when: environment != 'development'
