- hosts: all
  gather_facts: false

  vars:
    templates_path: "./templates"

  tasks:
    - name: ensure apps path exists
      file:
        path: "{{ apps_path }}"
        state: directory

    - name: setup env files
      template:
        src: "{{ templates_path }}/{{ item }}.j2"
        dest: "{{ project_path }}/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: +rwx
      with_items:
        - ".env"
        - "nginx_config"
        - "server.Dockerfile"
        - "unit.Dockerfile"
        - "ui.Dockerfile"
        - "docker-compose.yml"

    - name: run base services
      shell: docker-compose up -d db unit
      args:
        chdir: "{{ project_path }}"

    - name: run client and server
      shell: docker-compose up -d --build server ui
      args:
        chdir: "{{ project_path }}"
      when: env != 'development'

    - name: remove intermediate images
      shell: docker image prune --force
      args:
        chdir: "{{ project_path }}"
      when: env != 'development'
