- hosts: all
  gather_facts: false

  vars:
    templates_path: "./templates"

  tasks:
    - name: ensure apps path exists
      file:
        path: "{{ apps_path }}"
        state: directory

    - name: setup env files
      template:
        src: "{{ templates_path }}/{{ item }}.j2"
        dest: "{{ project_path }}/{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - ".env"
        - "docker-compose.yml"

    - name: log in to registry
      shell: echo {{ token }} | docker login -u gitlab-ci-token {{ registry }} --password-stdin
      when: environment != 'development'

    - name: pull changes
      shell: docker-compose pull
      args:
        chdir: "{{ project_path }}"

    - name: run base services
      shell: docker-compose up -d db unit
      args:
        chdir: "{{ project_path }}"

    - name: run server
      shell: docker-compose up -d server
      args:
        chdir: "{{ project_path }}"
      when: environment != 'development'
